# =============================================================================
# .latexmkrc — Latexmk Configuration
# =============================================================================
#
# Compiler: LuaLaTeX + Biber
# Usage:    latexmk          (builds main.pdf)
#           latexmk -c       (clean auxiliary files)
#           latexmk -C       (clean all generated files including PDF)
#

# Use LuaLaTeX as the PDF compiler
$pdflatex = 'lualatex -interaction=nonstopmode -halt-on-error -synctex=1 %O %S';

# Generate PDF directly (not via DVI or PS)
$pdf_mode = 1;

# Use biber for bibliography processing
$biber = 'biber %O %S';
$bibtex_use = 2;

# Main document
@default_files = ('main.tex');

# Clean additional auxiliary files generated by various packages
$clean_ext = 'bbl blg run.xml bcf fdb_latexmk fls synctex.gz '
           . 'nav snm vrb toc lof lot out aux log '
           . 'idx ind ilg gls glo glg acn acr alg '
           . 'ist nlo nls nlg';

# Maximum number of compilation runs
$max_repeat = 5;

# Show warnings about undefined references
$silence_logfile_warnings = 0;
